### PR TITLE
Release 1.0.0 : Apple Website Clone

### PR DESCRIPTION
**Pull request by mimipeshy**
Changelog
- Added background image
- Added navbar
- Added gradients to navbar section
- Used grid to create aside section
- Created the footer section

### CODE REVIEW

**Comment by santiago-dev96** [comment]
# Pull Request under review by @santiago-rodrig (TSE)

**Review by santiago-dev96 — CHANGES_REQUESTED** [review]
# Invalid PR :no_entry_sign:
This PR is invalid because of the following reasons.
1. The PR title is not descriptive

I have to make sure that you are following the professional standards in order for me to start any review.

Friendly reminder: You should make sure that your repo looks professional before review. Please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/). Then apply 3 simple rules from this lesson (it will be easy as you can use a template provided there). This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

Once you have implemented the required changes, submit another CRR (Code Review Request).

You can find me in slack as **srodrig**. Have a nice day :wave:!

**Comment by mimipeshy** [comment]
Changelog
- Updated README file with tips on how to use my website
- Removed redundant CSS lines
- Changed PR name

**Comment by rammazzoti2000** [comment]
### Hello @rida-elbahtouri :wave: 
As mentioned by the previous TSE this pull request was marked as invalid for the reasons mentioned above, and for that this pull request must be closed.
To make another code review request, open a new pulll request and make sure this time it looks professional (as suggested by the previous TSE)
#### 
For more clarifications you can find me on slack as `alexandru`. Happy coding :wave:

**Pull request closed without merging**
